### ISSUE TITLE
Связывание аккаунтов Я.Диалоги и приложение yandex2mqtt

### ISSUE THREAD

**Issue by Artemius5682** [Xoma163/yandex2mqtt#1]
Привет! Приглянулось твое приложение для связывания MQTT устройств, у меня есть вопросы, но пока что волнует только один. Смотри, django приложение я развернул, диалог создал и опубликовал. Остановился на моменте связки аккаунтов, в своем мануале ты пишешь, что надо выбрать устройства умного дома и пройти авторизацию, но у меня в Я.Диалоги почему-то негде выбрать устройства умного дома. Не подскажешь, в чем может быть проблема? Спасибо.
![image](https://user-images.githubusercontent.com/63748125/232622006-be939e63-83df-4215-97aa-d7f1e466d2e3.png)

**Comment by Xoma163** [comment]
Привет!
Сначала происходит линк аккаунтов, после этого Яндекс автоматически просканирует новые устройства у сервиса.
Если их нет - ничего страшного, можно будет добавить потом и попытаться добавить устройства из этого умного дома.

Насчёт 400. 

![image](https://user-images.githubusercontent.com/35608430/232957068-fcc2e1fd-1d10-4a2f-b2be-613aa6924f3a.png)
У меня выглядит вот так. В этом приложении есть фильтр на список устройств, он будет показывать только те, которые добавлены этим навыком. Там нужно нажать на плюсик и он предложит текущий навык для добавления.
![image](https://user-images.githubusercontent.com/35608430/232957241-35eae803-5164-4203-9b68-193e976b2811.png)
![image](https://user-images.githubusercontent.com/35608430/232957269-f28d4ebf-8995-492d-b6aa-3da3de485b0a.png)

Также можно попробовать это сделать с телефона. Разницы нет. Просто с телефона не будет видно почему именно происходит ошибка.

Странно, что у меня на скрине во вкладке тестирование заголовки называются "Умный дом" и "Тестирование", а у тебя "Чат" и "Последний запрос".

Что предшествовало этому скриншоту, какие действия на этой странице?

Правильно понимаю, что Яндекс слинковался с приложением по OAuth?
