### ISSUE TITLE
Вопрос по пользователям

### ISSUE THREAD

**Issue by rial2001** [Xoma163/yandex2mqtt#2]
Добрый день! Ещё не пробовал Ваш проект. Хотел уточнить: возможно ли реализовать многопользовательский вариант ( у каждого пользователя свои устройства, брокер один). Смотрю вариант для реализации небольшого проекта для публичного навыка. Заранее спасибо,

**Comment by Xoma163** [comment]
@rial2001 привет! Пилил давно, уже мало, что помню, да и сам пользоваться проектом перестал в угоду home assistant и аддонов типа Yaha Cloud от Alex и т.д... Если отвечать по памяти, то скорее всего такого функционала нет, но его достаточно несложно можно было бы расширить. Ну или взять тот же аналог на nodejs (называется также + есть ссылка в readme), если есть навыки js, то там это уже есть из коробки.
