### ISSUE TITLE
MySQL/Apache2 вместо PostrgeSQL/nginx

### ISSUE THREAD

**Issue by booroondook-eng** [Xoma163/yandex2mqtt#3]
Реально ли установить этот солюшн на БД MySQL и использование Apache2 в качестве веб-сервера?
Если реально, то как?
Просто уже есть готовая линукс-машина с указанными серверами БД и Web. Соответственно, не хочется городить дублирующие сервисы на других движках.

**Comment by Xoma163** [comment]
> Реально ли установить этот солюшн на БД MySQL и использование Apache2 в качестве веб-сервера? Если реально, то как? Просто уже есть готовая линукс-машина с указанными серверами БД и Web. Соответственно, не хочется городить дублирующие сервисы на других движках.

Вполне реально, но как именно законнектить джангу и apache - не знаю, не пробовал. Нужно гуглить
https://docs.djangoproject.com/en/5.0/howto/deployment/wsgi/modwsgi/

MySQL использовать можно, это настраивается [здесь](https://github.com/Xoma163/yandex2mqtt/blob/109f52380a71e0d718db196773a003ae09f19ce5/yandex2mqtt/settings.py#L96). Но сам DATABASE_URL указывается в .env [тут](https://github.com/Xoma163/yandex2mqtt/blob/master/.env_example).

Проект не поддерживается уже давно, возможно что-то изменилось, но скорее добавились новые сущности.
Я бы не рекомендовал его использовать, если не собираетесь допиливать в будущем, лучше посмотрите на аналоги

**Comment by Xoma163** [comment]
Чтобы запустить проект можно после установки всех зависимостей запустить его через `python manage.py runserver 8080`, это для локального тестирования и разработки, не для продакшена.
